### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by organofcorti** [siklon/cpuminer-gc3355#1]
Errors as follows (copypasta from console):

root@desktop:/home/ooc/cpuminer-gc3355# make
make  all-recursive
make[1]: Entering directory `/home/ooc/cpuminer-gc3355'
Making all in compat
make[2]: Entering directory`/home/ooc/cpuminer-gc3355/compat'
make[3]: Entering directory `/home/ooc/cpuminer-gc3355/compat'
make[3]: Nothing to be done for`all-am'.
make[3]: Leaving directory `/home/ooc/cpuminer-gc3355/compat'
make[2]: Leaving directory`/home/ooc/cpuminer-gc3355/compat'
make[2]: Entering directory `/home/ooc/cpuminer-gc3355'
gcc -std=gnu99  -O3 -lncurses -pthread  -o minerd minerd-cpu-miner.o minerd-util.o minerd-sha2.o minerd-scrypt.o  minerd-sha2-x64.o minerd-scrypt-x64.o  -L/usr/lib/x86_64-linux-gnu -lcurl -ljansson -lpthread  
minerd-cpu-miner.o: In function`clean_up':
cpu-miner.c:(.text+0x21): undefined reference to `curs_set'
cpu-miner.c:(.text+0x71): undefined reference to`endwin'
cpu-miner.c:(.text+0x82): undefined reference to `stdscr'
cpu-miner.c:(.text+0x87): undefined reference to`wclear'
minerd-cpu-miner.o: In function `tui_thread':
cpu-miner.c:(.text+0x313): undefined reference to`wmove'
cpu-miner.c:(.text+0x326): undefined reference to `wclrtoeol'
cpu-miner.c:(.text+0x498): undefined reference to`wmove'
cpu-miner.c:(.text+0x4ab): undefined reference to `wclrtoeol'
cpu-miner.c:(.text+0x589): undefined reference to`wmove'
cpu-miner.c:(.text+0x59c): undefined reference to `wclrtoeol'
cpu-miner.c:(.text+0x5dd): undefined reference to`wrefresh'
cpu-miner.c:(.text+0x5f0): undefined reference to `wrefresh'
minerd-cpu-miner.o: In function`init_tui':
cpu-miner.c:(.text+0x77f): undefined reference to `initscr'
cpu-miner.c:(.text+0x784): undefined reference to`cbreak'
cpu-miner.c:(.text+0x78b): undefined reference to `stdscr'
cpu-miner.c:(.text+0x795): undefined reference to`keypad'
cpu-miner.c:(.text+0x79a): undefined reference to `noecho'
cpu-miner.c:(.text+0x7a1): undefined reference to`curs_set'
cpu-miner.c:(.text+0x7a8): undefined reference to `stdscr'
cpu-miner.c:(.text+0x7ad): undefined reference to`wrefresh'
cpu-miner.c:(.text+0x7c3): undefined reference to `COLS'
cpu-miner.c:(.text+0x7f9): undefined reference to`wmove'
cpu-miner.c:(.text+0x80b): undefined reference to `COLS'
cpu-miner.c:(.text+0x81b): undefined reference to`whline'
cpu-miner.c:(.text+0x829): undefined reference to `COLS'
cpu-miner.c:(.text+0x85c): undefined reference to`wmove'
cpu-miner.c:(.text+0x86e): undefined reference to `COLS'
cpu-miner.c:(.text+0x87f): undefined reference to`whline'
cpu-miner.c:(.text+0x88d): undefined reference to `COLS'
cpu-miner.c:(.text+0x8d3): undefined reference to`wmove'
cpu-miner.c:(.text+0x8e5): undefined reference to `COLS'
cpu-miner.c:(.text+0x8f6): undefined reference to`whline'
cpu-miner.c:(.text+0x91d): undefined reference to `LINES'
cpu-miner.c:(.text+0x942): undefined reference to`COLS'
cpu-miner.c:(.text+0x96e): undefined reference to `wmove'
cpu-miner.c:(.text+0x980): undefined reference to`COLS'
cpu-miner.c:(.text+0x991): undefined reference to `whline'
cpu-miner.c:(.text+0xa0a): undefined reference to`mvwprintw'
cpu-miner.c:(.text+0xa21): undefined reference to `wmove'
cpu-miner.c:(.text+0xa34): undefined reference to`wclrtoeol'
cpu-miner.c:(.text+0xb10): undefined reference to `wmove'
cpu-miner.c:(.text+0xb23): undefined reference to`wclrtoeol'
cpu-miner.c:(.text+0xb73): undefined reference to `wmove'
cpu-miner.c:(.text+0xb86): undefined reference to`wclrtoeol'
cpu-miner.c:(.text+0xc45): undefined reference to `wrefresh'
cpu-miner.c:(.text+0xc58): undefined reference to`wrefresh'
cpu-miner.c:(.text+0xc6b): undefined reference to `wrefresh'
cpu-miner.c:(.text+0xc7e): undefined reference to`wrefresh'
cpu-miner.c:(.text+0xc85): undefined reference to `stdscr'
minerd-cpu-miner.o: In function`signal_handler':
cpu-miner.c:(.text+0x2820): undefined reference to `curs_set'
cpu-miner.c:(.text+0x2870): undefined reference to`endwin'
cpu-miner.c:(.text+0x2877): undefined reference to `stdscr'
cpu-miner.c:(.text+0x287c): undefined reference to`wrefresh'
cpu-miner.c:(.text+0x2883): undefined reference to `stdscr'
cpu-miner.c:(.text+0x2888): undefined reference to`wclear'
minerd-cpu-miner.o: In function `init_tui':
cpu-miner.c:(.text+0xc90): undefined reference to`wrefresh'
minerd-util.o: In function `new_win':
util.c:(.text+0x3d8): undefined reference to`newwin'
minerd-util.o: In function `del_win':
util.c:(.text+0x3f8): undefined reference to`delwin'
minerd-util.o: In function `update_stats_window':
util.c:(.text+0x414): undefined reference to`COLS'
minerd-util.o: In function `applog':
util.c:(.text+0x8e8): undefined reference to`COLS'
util.c:(.text+0x9e9): undefined reference to `wmove'
util.c:(.text+0x9fc): undefined reference to`wclrtoeol'
util.c:(.text+0xa32): undefined reference to `mvwprintw'
util.c:(.text+0xa58): undefined reference to`wrefresh'
minerd-util.o: In function `update_stats_window':
util.c:(.text+0x438): undefined reference to`mvwprintw'
collect2: error: ld returned 1 exit status
make[2]: **\* [minerd] Error 1
make[2]: Leaving directory `/home/ooc/cpuminer-gc3355'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/ooc/cpuminer-gc3355'
make: **\* [all] Error 2

**Comment by CartmanSPC** [comment]
Same here...

**Comment by bboerst** [comment]
I'm able to make just fine.  Just throwing this out there as a possibility - there was a new dependency (ncurses) added during this last commit so make sure that you have 'libncurses5-dev' installed:

apt-get install -y libncurses5-dev

**Comment by siklon** [comment]
You have to edit Makefile.am, and add "-L/usr/lib/x86_64-linux-gnu -lncurses" to the end of minerd_LDADD, then reconfigure (without -lncurses) and make
If the path to the curses lib differs, adjust accordingly.

**Comment by CartmanSPC** [comment]
@bboerst : Yes, I noticed that and added it before I tried to build. Still got the error.
@siklon : Thanks...will give that a try.

**Comment by CartmanSPC** [comment]
@siklon : That worked.

**Comment by siklon** [comment]
I have updated the configure.ac and Makefile for curses libs.
'make distclean ; ./autogen.sh ; ./configure CFLAGS="-O3"; make' should work right out of the box.

**Comment by organofcorti** [comment]
Worked for me too. Thanks!
