### ISSUE TITLE
Hashrate drops on blades

### ISSUE THREAD

**Issue by prolic** [siklon/cpuminer-gc3355#12]
See issue created at minera project:
https://github.com/michelem09/minera/issues/3

**Comment by siklon** [comment]
Honestly no idea why it occurs, I thought I fixed that. And I can't test since I don't own a Blade.

**Comment by siklon** [comment]
It would be worth checking the latest commit, it will set a global frequency if there is no specific chip frequency set. Try to run your Blades on one frequency. The Blades might not like if the frequency isn't set uniformly.

**Comment by prolic** [comment]
I tested your last commit. Didn't help.

**Comment by siklon** [comment]
Did you run the Blade on one frequency?

**Comment by prolic** [comment]
Yes, I use global freq=850.

**Comment by siklon** [comment]
Try changing https://github.com/siklon/cpuminer-gc3355/blob/master/gc3355-commands.h#L16
to `(unsigned char[]) {0x08, 0x55, 0xaa, 0x1f, 0x28, 0x16, 0x00, 0x00, 0x00},`
This is the same command cgminer uses.

**Comment by prolic** [comment]
I am currently testing this... stay tuned ;)

**Comment by prolic** [comment]
It seems to help at least a little together with the timeout option set. But still I get much better performance with cgminer without drops in the hashrate occuring.

**Comment by siklon** [comment]
Copied the reset method from cgminer in the last commit, you might want to try it.

**Comment by prolic** [comment]
I am testing this since 6h 40m. No problems so far, looks pretty good. I'll let you know tomorrow evening if the long-run test proves the success.

:+1:

**Comment by prolic** [comment]
22h 30m happy mining. Thank's a lot!
