### ISSUE TITLE
 C compiler cannot create executables

### ISSUE THREAD

**Issue by n3rvi0zz0** [siklon/cpuminer-gc3355#13]
hi have this problem wen i try to compile cpuminer

ruben@CloudHash:~/cpuminer-gc3355$ sudo ./configure CFLAGS="O3 -lncurses"
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/ruben/cpuminer-gc3355':
configure: error: C compiler cannot create executables
See`config.log' for more details

im check the config.log but i dont understand nothing any idea??? thanks for the help

**Comment by siklon** [comment]
Your configure command is totally wrong.
It should be: `./configure CFLAGS="-O3"`
Closing as this is not an cpuminer issue.
