### ISSUE TITLE
stats information

### ISSUE THREAD

**Issue by prolic** [siklon/cpuminer-gc3355#14]
I like to have some additional stats infos:
- which pool is currently mined on
- time used per pool
- hashes (accepted/rejected) per pool

**Comment by siklon** [comment]
As per request, pool info has been added to the API.
https://github.com/siklon/cpuminer-gc3355/commit/cbb59d70d6f3e2e721c9ef2f2baa085b6693cef1

**Comment by prolic** [comment]
wow! thanks! ;)
