### ISSUE TITLE
"stratum_recv_line failed" when using BetaRigs pools

### ISSUE THREAD

**Issue by quakefiend420** [siklon/cpuminer-gc3355#16]
These pools work just fine on my cgminer instances.

When trying either of these two pools:

stratum+tcp://r3026.g63.rigs.eu.betarigs.com:6192
http://eu.betarigs.com:3333

with -u qf420-3025 -p x

I just get the above error over and over again, it never submits a share.  My cgminer rigs are submitting shares on this worker with no issues as I type this.

CleverMining (stratum+tcp://ca.clevermining.com:3333) works fine.  Haven't tried any others yet.

I enabled debug mode, but it didn't give me much more info...

http://i.imgur.com/qOENVdR.png

I'm using this as part of the Minera distribution, 0.1.10a.

Anything else that I can do to help track down the issue, let me know!

**Comment by siklon** [comment]
Recv socket failed, which means the pool closed the socket when recv was called. It has nothing to do with cpuminer. BTW, same error on cgminer.

**Comment by quakefiend420** [comment]
You are absolutely right, I didn't notice that the port had changed as well.
