### ISSUE TITLE
Parameter gc3355-timeout=N doesn't seem to work for blades

### ISSUE THREAD

**Issue by Iggyboo** [siklon/cpuminer-gc3355#17]
I've had some Gridseed Blades that seem to get hung occasionally and will not reset and start submitting shared again. I've attempted to use --gc3355-timeout=320 to try to catch it but it doesn't seem to be working. I've seen it go as high as 5000+ without a share from the blade. I can restart cpuminer and it starts up again. It also doesn't seem to be the same blade each time.

**Comment by Iggyboo** [comment]
Ah maybe another issue: I just noticed this while watching the logs and I saw this

Resetting GC3355 chips 
UART write error

Then it terminates the thread and stops dispatching work to that blade.  A different problem or related? This is probably why the time between share goes up but then it doesn't restart the thread. Is this intentional?

**Comment by Iggyboo** [comment]
Well ... a bit more of asking "The Goog", I think I found this to be a USB HUB/Cord/Connection issue. I've fiddled with all my cords and moved them around a bit on the hub to verify.

**Comment by Iggyboo** [comment]
Well ... now I feel silly :-)  I've been running solid since I've re-jiggered my cords and HUB.  As Rick Parry says ... Oops.  /:-)   Closing!

**Comment by siklon** [comment]
Yes, "UART write error" is caused by an intermittent USB connection. Glad to see that you have resolved it.
