### ISSUE TITLE
Per Chip Speeds in Autotune.

### ISSUE THREAD

**Issue by celly** [siklon/cpuminer-gc3355#18]
While running auto tune there is no way to get the current per-chip speeds. Only the device average/max?

**Comment by siklon** [comment]
Yes there is, that's what the API is used for.

**Comment by celly** [comment]
Yup. got it now. 

I was having issues with the API killing the parent process. Not 100% reproducible, but when it worked the API was always showing 850. After getting it to run stable for a while I was able to get the adjusted speeds. But, {"get":"stats"} still randomly kills the parent process, but sets work flawlessly.

Thanks! Should be good for now.
