### ISSUE TITLE
Howto: Solo Mining

### ISSUE THREAD

**Issue by prolic** [siklon/cpuminer-gc3355#19]
Is it possible to do solo mining with it?

**Comment by siklon** [comment]
No.

**Comment by prolic** [comment]
:-( ok

**Comment by SmittyHalibut** [comment]
Is the question "Does it support Getwork?" the same as this ticket?  I give it an http URL and it still tries to connect Stratum to my wallet.  Is this an intentional thing?

I'm mining DefCoin with a difficulty of about 1.0 right now; solo mining is definitely effective here.

**Comment by siklon** [comment]
It does not support getwork, that is a deprecated protocol.
