### ISSUE TITLE
Gridseed gc3355 not recognized and don't mine on Raspberry pi

### ISSUE THREAD

**Issue by ziouf** [siklon/cpuminer-gc3355#2]
From ./minerd :

```
 [2014-04-30 17:37:16] 0: Invalid response while reading firmware version
 [2014-04-30 17:37:16] 0: Firmware version: 0xffffffff
 [2014-04-30 17:37:16] 0: Unknown GC3355 Miner detected (chips=5)"
```

I used your binary for raspberry pi (from https://www.dropbox.com/s/xc3lvysi8vtrt00/minerd-gc3355)
 And I tried to compile it from sources.

Same issue in the two cases

I use a Raspberry Pi model B with Raspbian Wheezy.

**Comment by siklon** [comment]
Which miner (USB/Blade) are you using it with?
Usually this indicates a communication problem related to the MCU chip, the USB and 12V need to be power cycled.

**Comment by ziouf** [comment]
I have a 5 chips USB miner.
It works well with cgminer. but not with cpuminer.
I unplugged and replugged the USB and power supply. No change.

**Comment by siklon** [comment]
Did you try rebooting the RPi and directly running cpuminer as well?
What is RPi's kernel version?
Seems like you're the only one with this issue, that still persists after power cycling.

**Comment by ziouf** [comment]
```
uname -a
> Linux raspberrypi 3.10.25+ #622 PREEMPT Fri Jan 3 18:41:00 GMT 2014 armv6l GNU/Linux
```

The issue is still there when I reboot the PI, or after power cycling and directly running cpuminer.

**Comment by ziouf** [comment]
I would add that my miner is recognised as ttyAMA0 and not ttyACM0.
Is there a link with the issue?

**Comment by siklon** [comment]
Ok, so you're using the wrong port. Gridseed devices only use /dev/ttyUSB or /dev/ttyACM.
It is explained in the docs that cgminer may interfere, but it is usually solved after rebooting, and not starting cgminer thereafter..

**Comment by ziouf** [comment]
Sorry for the newby question, but, getty is connecting gc3355 automatically to ttyAMA0. 
How can I force it to the right one ?

**Comment by ziouf** [comment]
Ok i found how to set up ttyACM0 and cpuminer recognize the miner
But no mining. Hashrate stay at 0...

**Comment by ziouf** [comment]
ok Problem solved. It was a permission issue on /dev/ttyACM0.
Thanks for your help and your time.

Regards
