### ISSUE TITLE
gc-detect issue with heterogeneous setup (GSD with non-GSD devices)

### ISSUE THREAD

**Issue by highwalker** [siklon/cpuminer-gc3355#9]
Hi,

I believe that using --gc-detect has a bug that it assumes that all ASIC USB devices are also GSD. For example I also have AntMiner running which is seen on the lsusb as:
Bus 001 Device 011: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light

and the GSD is seen as:

Bus 001 Device 009: ID 0483:5740 SGS Thomson Microelectronics

This leads to the unforeseen behavior:
1. cpu-miner shows 4 devices instead of 2 (as in my case I have 2 GSD 5 chip)
2. minerd attempts to set baud rate on the UART of the AntMiner (which is already being accessed by bfgminer separately) causing weird behavior (since both apps are running as setuid root, if the UART port access is granted then the bfgminer hangs or minerd hangs or spits unable to read logs and crashes).

Perhaps using the device ID (0483:5470) to isolate the GSD devices for the detect routine might be a better idea. As far as I know, this is the dev id for all GSD 5 chip miner's although I am not sure of the GSD blade miner, I would guess since the same MCU is being used, the dev id might be same.

I also noticed a USB reset also on the bus (I am not sure the enumerate_dev causes a reset or not) although I am not sure if its caused by minerd (could also be by bfgminer as well to regain USB dev access).

Hope this info helps. Let me know if you need to run any debug or details to help you look into this.

Thanks,

BR,

KK

**Comment by siklon** [comment]
I guess that Antminer and GSD (red unit) use the same MCU, which in that case it would be hard to distinguish one from another without sending GSD commands to read the MCU registers.

There is no USB reset, only the iteration of devices using udev.

**Comment by highwalker** [comment]
Ugh, sorry and I understand this is tough. Could you use the length of the serial to distinguish between the two? I noted that you are filtering using the vendor ID & product ID already. Antminers have 4 characters GSD's have 12.

**Comment by siklon** [comment]
Actually the red GSD have the same serial string, this is the dev info from a GSD:

```
P:  Vendor=10c4 ProdID=ea60 Rev= 1.00
S:  Manufacturer=Silicon Labs
S:  Product=CP2102 USB to UART Bridge Controller
S:  SerialNumber=0001
C:* #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=100mA
I:* If#= 0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=00 Prot=00 Driver=cp210x
```
